version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streamingdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  python-app:
    build:
      context: ../  # Assuming docker-compose.yml is inside the docker/ directory and you want to include the app/ directory which is outside
      dockerfile: docker/Dockerfile
    container_name: project_one-python-app
    depends_on:
      - kafka
      - postgres
    volumes:
      - ../app:/app  # Ensure this points to the correct directory where your app.py and requirements.txt are located
    ports:
      - "5001:5002"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    command: python app.py

volumes:
  postgres-data:
